version: "3.9"
services:

  # sentinel-dashboard:
  #  build: ./sentinel-dashboard
  #  ports:
  #    - "0.0.0.0:6060:6060"
  #  networks:
  #    - backend
  #  depends_on: 
  #    - auth-service-web
  #    - file-service

  file-service:
    build: ./file-service
    env_file:
      - ./backend.env
    # ports:   
    # - "0.0.0.0:8082:8082"
    # - "0.0.0.0:7010:7010"
    volumes:
      - /home/zhuangyongj/file:/home/zhuangyongj/file
    networks:
      - backend
    restart: on-failure
    depends_on:
      - auth-service
    command:
      "java \
       -Dcom.sun.management.jmxremote \ 
       -Dcom.sun.management.jmxremote.rmi.port=7010 \ 
       -Dcom.sun.management.jmxremote.port=7010 \ 
       -Dcom.sun.management.jmxremote.authenticate=false \
       -Dcom.sun.management.jmxremote.ssl=false \ 
       -Dcom.sun.management.jmxremote.local.only=false \ 
       -jar -Xmx500m file-server-1.0.0.jar \
       --spring.profiles.active=test \ 
       --dubbo.protocol.port=-1 \
       --server.port=8082" 

  # -Djava.rmi.server.hostname=192.168.10.128

  auth-service-web:
    build: ./auth-service-web
    env_file:
      - ./backend.env
    # ports:   
    #  - "0.0.0.0:8084:8084"
    #  - "0.0.0.0:7011:7011"
    networks:
      - backend
    restart: on-failure
    depends_on:
      - auth-service
    command:
      "java \
       -Dcom.sun.management.jmxremote \ 
       -Dcom.sun.management.jmxremote.rmi.port=7011 \ 
       -Dcom.sun.management.jmxremote.port=7011 \ 
       -Dcom.sun.management.jmxremote.authenticate=false \
       -Dcom.sun.management.jmxremote.ssl=false \ 
       -Dcom.sun.management.jmxremote.local.only=false \ 
       -jar -Xmx500m auth-service-web-1.0.0.jar \ 
       --spring.profiles.active=test \
       --dubbo.protocol.port=-1 \
       --server.port=8084"

  auth-service:
    build: ./auth-service 
    env_file: 
      - ./backend.env
    # ports:
    #  - "0.0.0.0:7012:7012"
    networks:
      - backend 
    restart: on-failure
    command:
      "java \
       -Dcom.sun.management.jmxremote \ 
       -Dcom.sun.management.jmxremote.rmi.port=7012 \ 
       -Dcom.sun.management.jmxremote.port=7012 \ 
       -Dcom.sun.management.jmxremote.authenticate=false \
       -Dcom.sun.management.jmxremote.ssl=false \ 
       -Dcom.sun.management.jmxremote.local.only=false \ 
       -jar -Xmx500m auth-service-1.0.0.jar \
       --spring.profiles.active=test \
       --dubbo.protocol.port=-1 \
       --server.port=8080"

  nginx:
    image: nginx:alpine
    volumes:
      - /home/zhuangyongj/services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/zhuangyongj/services/nginx/cert:/etc/nginx/cert
      - /home/zhuangyongj/services/nginx/html:/usr/share/nginx/html/ 
    ports:
      - "0.0.0.0:8001:8001"
      - "0.0.0.0:8002:8002"
    networks:
      - backend
    restart: on-failure 

     # prometheus:
     # container_name: prometheus
     # image: prom/prometheus:latest
     # volumes:
     # - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
     # ports:
     # - "0.0.0.0:9090:9090"
     # depends_on:
     # - auth-service
     # - auth-service-web
     # - file-service
     # restart: on-failure

    #  grafana:
    # container_name: grafana
    # image: grafana/grafana:latest
    # ports:
    #   - "0.0.0.0:3000:3000"
    # depends_on:
    #   - auth-service
    #   - auth-service-web
    #   - file-service
    # restart: on-failure

networks:
  backend:
