package com.yongj.dao;

import java.util.List;

/**
 * Mapper for FileInfo
 *
 * @author yongjie.zhuang
 */
public interface FileInfoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_info
     *
     * @mbg.generated Thu Jun 10 23:48:40 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_info
     *
     * @mbg.generated Thu Jun 10 23:48:40 CST 2021
     */
    int insert(FileInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_info
     *
     * @mbg.generated Thu Jun 10 23:48:40 CST 2021
     */
    FileInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_info
     *
     * @mbg.generated Thu Jun 10 23:48:40 CST 2021
     */
    List<FileInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_info
     *
     * @mbg.generated Thu Jun 10 23:48:40 CST 2021
     */
    int updateByPrimaryKey(FileInfo record);
}